version: '3.8'

services:
  minio:
    build:
      context: .
      dockerfile: Dockerfile.telegram
    container_name: minio-telegram
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    dns:
      - 8.8.8.8
      - 1.1.1.1
    command: server /data --console-address ":9001"
    restart: unless-stopped
